const image = [
  'https://media.gq.com/photos/56d4902a9acdcf20275ef34c/master/w_806,h_1173,c_limit/tom-hardy-lead-840.jpg',
  'https://www.guideposts.org/sites/guideposts.org/files/styles/hero_box_left_lg/public/story/dick_van_dyke_marquee.jpg',
  'http://shared.frenys.com/assets/1009731/6151100-Young-Harrison-Ford.jpg',
  'https://www.famousbirthdays.com/faces/efron-zac-image.jpg',
  'https://resizing.flixster.com/zYHoIjM-IBcqyt8S3ZJzudd9E24=/fit-in/1152x864/v1.cjszOTU0NDtqOzE4MDAwOzEyMDA7MzkyOzYwMA',
  'http://shared.frenys.com/assets/1009731/6163548-Young-Kevin-Costner.jpg',
  'http://shared.frenys.com/assets/1009731/6162443-Josh-Hartnett.jpg',
  'http://shared.frenys.com/assets/1009731/6154108-Shawn-Ashmore.jpg',
  'http://shared.frenys.com/assets/1009731/6153211-Liam-Hemsworth.jpg',
  'http://shared.frenys.com/assets/1009731/6152500-Seann-William-Scott.jpg',
  'http://shared.frenys.com/assets/1009731/6149406-Jake-Gyllenhaal.jpg',
  'http://shared.frenys.com/assets/1009731/6147763-Tom-Weeling.jpg',
  'http://shared.frenys.com/assets/1009731/6146799-Darin-Brooks.jpg',
  'http://shared.frenys.com/assets/1009731/6142216-Joe-Anderson.jpg',
  'http://shared.frenys.com/assets/1009731/6140487-Mark-Wahlberg.jpg',
  'http://shared.frenys.com/assets/1009731/6138130.jpg',
  'http://shared.frenys.com/assets/1009731/6138129.jpg',
  'http://shared.frenys.com/assets/1009731/6136248.jpg',
  'http://shared.frenys.com/assets/1009731/6131539.jpg',
  'http://shared.frenys.com/assets/1009731/6118412.jpg',
  'http://shared.frenys.com/assets/1009731/6076453.jpg',
  'http://shared.frenys.com/assets/1009731/6075688.jpg',
  'http://shared.frenys.com/assets/1009731/6071869.jpg',
  'http://shared.frenys.com/assets/1009731/6068349.jpg',
  'http://shared.frenys.com/assets/1009731/6053633.jpg',
];

export const fakeData = [
  {
    matchUserGuid: '1',
    matchRoomGuid: '1',
    matchFirstName: 'Anteater',
    matchLastName: 'Anteater',
    matchLikesArray: ['Sport', 'Gym', 'Hiking'],
    matchImageUrl: image[0],
    matchMiles: '4.26',
    matchAge: '1',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '2',
    matchRoomGuid: '2',
    matchFirstName: 'Bear',
    matchLastName: 'Bear',
    matchLikesArray: ['Cooking', 'Gym', 'Movie'],
    matchImageUrl: image[1],
    matchMiles: '4.26',
    matchAge: '2',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '3',
    matchRoomGuid: '3',
    matchFirstName: 'Cat',
    matchLastName: 'Cat',
    matchLikesArray: ['Anime', 'Hiking', 'Manga'],
    matchImageUrl: image[2],
    matchMiles: '4.26',
    matchAge: '3',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '4',
    matchRoomGuid: '4',
    matchFirstName: 'Dog',
    matchLastName: 'Dog',
    matchLikesArray: ['Games', 'Coding', 'Studying'],
    matchImageUrl: image[3],
    matchMiles: '4.26',
    matchAge: '4',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '5',
    matchRoomGuid: '5',
    matchFirstName: 'Elephant',
    matchLastName: 'Elephant',
    matchLikesArray: ['Streaming', 'Gym', 'Chatting'],
    matchImageUrl: image[4],
    matchMiles: '4.26',
    matchAge: '5',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '6',
    matchRoomGuid: '6',
    matchFirstName: 'Fox',
    matchLastName: 'Fox',
    matchLikesArray: ['Sport', 'Games', 'Talking'],
    matchImageUrl: image[5],
    matchMiles: '4.26',
    matchAge: '6',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '7',
    matchRoomGuid: '7',
    matchFirstName: 'Giraffe',
    matchLastName: 'Giraffe',
    matchLikesArray: ['Presenting', 'Awwing', 'Shopping'],
    matchImageUrl: image[6],
    matchMiles: '4.26',
    matchAge: '7',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '8',
    matchRoomGuid: '8',
    matchFirstName: 'Hippo',
    matchLastName: 'Hippo',
    matchLikesArray: ['Idking', 'Loling', 'Awwing'],
    matchImageUrl: image[7],
    matchMiles: '4.26',
    matchAge: '8',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '9',
    matchRoomGuid: '9',
    matchFirstName: 'Iguana',
    matchLastName: 'Iguana',
    matchLikesArray: ['Hmming', 'Hmming', 'Hmming'],
    matchImageUrl: image[8],
    matchMiles: '4.26',
    matchAge: '9',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '10',
    matchRoomGuid: '10',
    matchFirstName: 'Jaguar',
    matchLastName: 'Jaguar',
    matchLikesArray: ['Awwing', 'Awwing', 'Awwing'],
    matchImageUrl: image[9],
    matchMiles: '4.26',
    matchAge: '10',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '11',
    matchRoomGuid: '11',
    matchFirstName: 'Kangaroo',
    matchLastName: 'Kangaroo',
    matchLikesArray: ['Eating', 'Eating', 'Eating'],
    matchImageUrl: image[10],
    matchMiles: '4.26',
    matchAge: '11',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '12',
    matchRoomGuid: '12',
    matchFirstName: 'Lizard',
    matchLastName: 'Lizard',
    matchLikesArray: ['Music', 'Song', 'Listening'],
    matchImageUrl: image[11],
    matchMiles: '4.26',
    matchAge: '12',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '13',
    matchRoomGuid: '13',
    matchFirstName: 'Mandrill',
    matchLastName: 'Mandrill',
    matchLikesArray: ['Guitar', 'Piano', 'Trumpet'],
    matchImageUrl: image[12],
    matchMiles: '4.26',
    matchAge: '13',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '14',
    matchRoomGuid: '14',
    matchFirstName: 'Nilgai',
    matchLastName: 'Nilgai',
    matchLikesArray: ['A', 'B', 'C'],
    matchImageUrl: image[13],
    matchMiles: '4.26',
    matchAge: '14',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '15',
    matchRoomGuid: '15',
    matchFirstName: 'Octopus',
    matchLastName: 'Octopus',
    matchLikesArray: ['C', 'D', 'E'],
    matchImageUrl: image[14],
    matchMiles: '4.26',
    matchAge: '15',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
  {
    matchUserGuid: '16',
    matchRoomGuid: '16',
    matchFirstName: 'Peacock',
    matchLastName: 'Peacock',
    matchLikesArray: ['E', 'F', 'G'],
    matchImageUrl: image[15],
    matchMiles: '4.26',
    matchAge: '16',
    matchCity: 'Some City',
    matchState: 'Some State',
  },
];
